networks:
    internal_net:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
        driver_opts:
            com.docker.network.driver.mtu: 65535
    external_net:
        ipam:
            driver: default
            config:
                - subnet: 42.42.0.0/16
                  gateway: 42.42.42.1
        driver_opts:
            com.docker.network.driver.mtu: 65535
services:
    client1:
        build: client1/
        image: oqs-bind
        stdin_open: true
        privileged: true
        tty: true
        dns: 172.20.0.2
        cap_add:
           - NET_ADMIN
        entrypoint: /bin/bash
        networks:
            internal_net:
                ipv4_address: 172.20.0.11
            external_net:
                ipv4_address: 42.42.42.3
    resolver:
        build:
            context: resolver/
            args:
                LISTENIP: 172.20.0.2
        image: oqs-bind
        entrypoint:
            - /init.bash
        stdin_open: true
        privileged: true
        tty: true
        networks:
            internal_net:
                ipv4_address: 172.20.0.2
        volumes:
            - dsset-volume:/dsset
            - ./scripts/init_resolver.bash:/init.bash
            - ./scripts/install_trust_anchor.bash:/install_trust_anchor.bash
            - ./bind-config/named-resolver.conf:/named.conf
            - ./bind-config/root.hints:/root.hints
        cap_add:
           - CAP_NET_ADMIN
    ns1_root:
        build:
            context: ns1.root./
            args:
                LISTENIP: 172.20.0.3
        image: oqs-bind
        entrypoint:
            - /init.bash
        stdin_open: true
        privileged: true
        tty: true
        networks:
            internal_net:
                ipv4_address: 172.20.0.3
        volumes:
            - dsset-volume:/dsset
            - ./scripts/add_ds.bash:/add_ds.bash
            - ./scripts/move_ds.bash:/move_ds.bash
            - ./zones/db.root:/db.root
            - ./bind-config/named-root.conf:/named.conf
            - ./scripts/init_root.bash:/init.bash
        cap_add:
           - CAP_NET_ADMIN
    ns1_example:
        build:
            context: ns1.example./
            args:
                LISTENIP: 172.20.0.4
        image: oqs-bind
        entrypoint:
            - /init.bash
        stdin_open: true
        privileged: true
        tty: true
        networks:
            internal_net:
                ipv4_address: 172.20.0.4
        volumes:
            - dsset-volume:/dsset
            - ./scripts/add_ds.bash:/add_ds.bash
            - ./scripts/move_ds.bash:/move_ds.bash
            - ./zones/db.example:/db.example
            - ./bind-config/named-example.conf:/named.conf
            - ./scripts/init_example.bash:/init.bash
        cap_add:
           - CAP_NET_ADMIN
volumes:
    dsset-volume:
